# Generated by Django 3.2.6 on 2022-05-14 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisorid',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trxid',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
