# Generated by Django 3.2.6 on 2022-05-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0003_alter_transaction_trx_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
