# Generated by Django 3.2.6 on 2022-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0004_alter_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATION', 'Corporation'), ('TRUST', 'Trust'), ('FOUNDATION', 'Foundation')], default='INDIVIDUAL', max_length=50),
        ),
    ]
