# Generated by Django 3.2.6 on 2022-05-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0005_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='security',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='singleclient.security'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INSTRUMENT-CASHFLOW', 'instrument-cashflow')], max_length=50),
        ),
    ]
