# Generated by Django 3.2.6 on 2022-05-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0006_auto_20220519_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mv', models.DecimalField(decimal_places=5, max_digits=15)),
                ('pnl', models.DecimalField(decimal_places=5, max_digits=15)),
                ('retrn', models.DecimalField(decimal_places=5, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singleclient.account')),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='singleclient.security')),
            ],
            options={
                'unique_together': {('account', 'security', 'date')},
            },
        ),
    ]
