# Generated by Django 3.2.6 on 2022-05-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0007_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='pnl',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='position',
            name='retrn',
        ),
    ]
