# Generated by Django 3.2.6 on 2022-05-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0008_auto_20220520_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='mv',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singleclient.security'),
        ),
    ]
