# Generated by Django 3.2.6 on 2022-05-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleclient', '0009_auto_20220521_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trx_type',
            field=models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell'), ('DEPOSIT', 'deposit'), ('WITHDRAWAL', 'withdrawal'), ('INSTRUMENT-CASHFLOW', 'instrument-cashflow')], max_length=50),
        ),
    ]
